---
title: "ggplot 2"
author: "Alicia Yang"
date: "10/01/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggridges)
library(patchwork)
```

##create the weather data
##creating month variable by rounding down 
```{r load_data, cache = TRUE}
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
  select(name, id, date, month, everything())
```
##grouping by function & counting
##n_obs = counting
```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(
    n_obs = n(),
    n_unique = n_distinct(date))
```

```{r}
weather_df %>%
  count(name, month)
```


##should not use table() (base-R's table) function
```{r}
weather_df %>%
  pull(name) %>%
  table()
```

(let's make nice table)
```{r}
weather_df %>%
  count(name) %>%
  knitr::kable()
```

##(2X2 tables)

a digression...

```{r}
weather_df %>%
  filter(name!="Waikiki_HA") %>%
  mutate(
    cold = case_when(
      tmax < 5 ~"cold", 
      tmax >= 5 ~ "not cold", 
      TRUE      ~ ""
    )
  ) %>%
  group_by(name, cold) %>%
  count() %>%
  pivot_wider(
    names_from = cold, 
    values_from = n
  )
```

```{r}
weather_df %>%
  filter(name!="Waikiki_HA") %>%
  mutate(
    cold = case_when(
      tmax < 5 ~"cold", 
      tmax >= 5 ~ "not cold", 
      TRUE      ~ ""
    )
  ) %>%
  janitor::tabyl(name, cold)
```

## general summaries

```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(
    n = n(), 
   mean_tmax = mean(tmax, na.rm = TRUE),
   sd_tmax = sd(tmax, na.rm = TRUE),
   median_prcp = median(prcp, na.rm = TRUE)
  ) %>%
  ggplot(aes(x = month, y = mean_tmax, color = name)) + 
  geom_point() + geom_line()
```


```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(
   mean_tmax = mean(tmax, na.rm = TRUE),
  ) %>%
  pivot_wider (
  )
```

##grouped mutates
(don't forget you can ungroup things)
```{r}
weather_df %>%
  group_by(name) %>%
  ungroup()
```

```{r}
weather_df %>%
  group_by(name) %<%
  mutate(
    mean_tmax = mean(tmax, na.rm = TRUE),
    centered_tmax = tmax - mean_tmax
  ) %>%
  ggplot(aes(x = date, y = centered_tmax, color = name)) + 
  geom_point()
```

window functinos in grouped mutates...

```{r}
weather_df %>%
  group_by(name, month) %>%
  mutate(
    tmax_rank = min_rank(tmax)
  ) %>% 
  filter(tmax_rank == 1) %>% view
```

lags and leads...

```{r}
weather_df %>%
  group_by(name) %>%
  mutate(
    lagged_tmax = lag(tmax), 
    one_day_tmax_change = tmax - lagged_tmax
  ) %>%
  summarize(sd_daily_change = sd(one_day_tmax_change, na.rm = TRUE))
```
